#!/usr/bin/env python3

import os
import re
import sys
import argparse

DESCR = """afl-qemu-total-cov1.0
Written and maintained by Andrea Fioraldi <andreafioraldi@gmail.com>
"""

opt = argparse.ArgumentParser(description=DESCR, formatter_class=argparse.RawTextHelpFormatter)
opt.add_argument('-l', help="Log CSV of afl-qemu-cov", action='store', required=True)

args = opt.parse_args()

with open(args.l) as f:
    log = filter(lambda x: not x.startswith("#"), f.readlines())
    log = map(lambda x: map(lambda y: y.strip(), x.split(",")), log)

bbs = {}
for testcase_id, bb_addr in log:
    bbs.add(bb_addr)

print("Number of Basic Blocks:", len(bbs))
